# fly.toml app configuration file generated for yo-activities on 2023-04-18T22:31:56+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yo-activities"
primary_region = "jnb"

[build]
  image = "justinkokolo/reactivities:latest"

 [env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="dj3wmuy3l"
  Cloudinary__ApiKey="895484589483755" 

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
